import { z } from "zod";

const quantitySchema = z.coerce.number().int().min(0).max(99);
export const addItemSchema = z.object({ productId: z.coerce.number().int().positive(), quantity: z.coerce.number().int().min(1).max(99), variationId: z.coerce.number().int().positive().optional() });
export const updateQuantitySchema = z.object({ quantity: quantitySchema.refine((quantity) => quantity > 0, "Quantity must be at least one; use removeItem to remove an item.") });
export const addressSchema = z.object({ firstName: z.string().trim().max(100).optional(), lastName: z.string().trim().max(100).optional(), company: z.string().trim().max(100).optional(), address1: z.string().trim().max(200).optional(), address2: z.string().trim().max(200).optional(), city: z.string().trim().max(100).optional(), state: z.string().trim().max(100).optional(), postcode: z.string().trim().max(20).optional(), country: z.string().trim().length(2).optional(), email: z.string().email().max(254).optional(), phone: z.string().trim().max(30).optional() }).strict();
export const updateCustomerSchema = z.object({ billingAddress: addressSchema.optional(), shippingAddress: addressSchema.optional() }).refine((input) => input.billingAddress || input.shippingAddress, "At least one address is required.");
export const selectShippingRateSchema = z.object({ packageId: z.coerce.number().int().nonnegative(), rateId: z.string().trim().min(1).max(200) });

const moneySchema = z.object({ amount: z.string().regex(/^\d+$/), currencyCode: z.string().length(3), minorUnit: z.number().int().min(0).max(4) });
export const cartSchema = z.object({ items: z.array(z.object({ key: z.string().min(1), productId: z.number().int().positive(), variationId: z.number().int().positive().optional(), name: z.string(), quantity: z.number().int().positive(), price: moneySchema, imageUrl: z.string().url().optional() })), totals: z.object({ totalItems: moneySchema, totalShipping: moneySchema, totalTax: moneySchema, totalPrice: moneySchema }), shippingRates: z.array(z.object({ packageId: z.number().int().nonnegative(), selectedRate: z.string().nullable(), rates: z.array(z.object({ rateId: z.string(), name: z.string(), price: moneySchema, selected: z.boolean() })) })) });
export const upstreamCartSchema = z.object({ items: z.array(z.object({ key: z.string(), id: z.number().int(), quantity: z.number().int(), name: z.string(), variation: z.array(z.unknown()).optional(), prices: z.object({ price: z.string(), currency_code: z.string().length(3), currency_minor_unit: z.number().int() }), image: z.object({ src: z.string().url() }).optional() })), totals: z.object({ total_items: z.string(), total_shipping: z.string(), total_tax: z.string(), total_price: z.string(), currency_code: z.string().length(3), currency_minor_unit: z.number().int() }), shipping_rates: z.array(z.object({ package_id: z.number().int(), rates: z.array(z.object({ rate_id: z.string(), name: z.string(), price: z.string(), selected: z.boolean() })) })).default([]) });
